#+title: qutebrowser configuration
#+author: Giovanni Crisalfi
#+date: 2022-12-03 sab 22:02
#+hugo_base_dir: ~/zwitterio-it/
#+hugo_section: software/qute-config
#+export_file_name: index.en.md
#+hugo_tags: vim qt python
#+hugo_categories: software
#+STARTUP: overview
#+MACRO: more @@html:<!-- more -->@@

#+begin_quote
qutebrowser is a keyboard-focused browser with a minimal GUI. It’s based on Python and Qt and free software, licensed under the GPL.
#+end_quote

{{{more}}}

It's said "cute browser", because it's actually cute, yes, but mostly because that's how Qt itself is pronounced. *Stay and enjoy the quteness*.

#+begin_quote
Wait, but isn't Python /ToO sLoW/ for a browser?
#+end_quote

*No.*

* Globals
[[https://www.qutebrowser.org/doc/help/configuring.html][From the docs]]:

#+begin_quote
For more powerful configuration possibilities, you can create a =config.py= file. Since it’s a Python file, you have much more flexibility for configuration. Note that qutebrowser will never touch this file - this means you’ll be responsible for updating it when upgrading to a newer qutebrowser version.
#+end_quote

Going further in this literate configuration, I will cite the docs a lot more.

#+begin_quote
Two global objects are pre-defined when running =config.py=: c and config.
#+end_quote

So, let's start from them:

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
config = config  # type: ConfigAPI
c = c  # type: ConfigContainer
#+end_src

This isn't enough, because we must tell qutebrowser if we want to load autoconfig or not. If we forgot this, qutebrowser will throw this error:

#+begin_quote
autoconfig loading not specified: Your config.py should call either `config.load_autoconfig()` (to load settings configured via the GUI) or `config.load_autoconfig(False)` (to not do so)
#+end_quote

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)
#+end_src

#+begin_quote
See the [[https://www.qutebrowser.org/doc/help/settings.html][settings help page]] for all available settings.
#+end_quote

* Fonts
#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# Default font families to use.
c.fonts.default_family = "Noto Sans Mono"

# Default font size to use.
# c.fonts.default_size = "11pt"
#+end_src

* Cookies
#+begin_quote
Which cookies to accept.
#+end_quote

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'no-3rdparty', 'chrome-devtools://*')
#+end_src

* Keybindings
** Emacs-y launcher (a basic example)
#+begin_quote
While it’s possible to change the =bindings.commands= setting to customize the keyboard shortcuts, it’s preferred to use the =config.bind= command. Doing so ensures the commands are valid and normalizes different expressions which map to the same key.
#+end_quote

First of all, I want an emacs-like binding to launch commands.

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# Emacs-y way to launch commands
config.bind('<Alt-x>', 'set-cmd-text :')
#+end_src

Why using an emacs-like binding with a vi-like configuration, you might say. It's a good question, but the answer is really simple: I'm an Evil Emacs user and I live on the great Doom Emacs distribution, so I'm used to a (IMO) optimal blending of both the styles with some "space spice" on them. Like Spacemacs, Doom Emacs promotes the use of the space key for launching a lot of commands. I wish I could try to emulate this behaviour in this qutebrowser config too.

** The power of space sequences
# This isn't easy as I hoped, because the leading key isn't really something qutebrowser expects.
# The keybindings aren't thought to be sequential, like they are on Spacemacs.

My keybindings turn around *<Space>*.

Since I falled in space-centered key settings when I first installed Spacemacs, I'll let them teach why =<Space>= is so comfortable. From Spacemacs' docs:

#+begin_quote
[[https://develop.spacemacs.org/doc/BEGINNERS_TUTORIAL.html][The power of Spacemacs lies in its efficient key bindings.]]

[...]

Because the spacebar is the most accessible key on the keyboard and is pressed by the strongest fingers (the thumbs), it is a natural choice for launching commands. You can think of it as the start menu of Spacemacs.
#+end_quote

Of course, I don't demand having =<Space>= as an entry point for a qutebrowser's "start menu": just being able to launch my usual sequences would be enough.
From qutebrowser docs:

#+begin_quote
To bind keys without modifiers, specify a key chain to bind as a string.
#+end_quote

By exploring the docs, I found out that in the language of qutebrowser, *sequences are called /keychains/*.
When a key is linked to more keychains, qutebrowser shows the so called "keyhint", which is a little cheatsheet on the side of your screen.
It's not like having a full functional buffer popping up everytime you need it like in Spacemacs or Doom Emacs, but it's pretty similar for our purpose!

A typical keychain looks like this one:

#+begin_quote
=Sq=: bookmark-list
#+end_quote

*Watch out!*: keychains are made by writing the keys all linked together, without spaces.

If keychains are possible with the letter "g" or "k", why shouldn't be possible with "Space", right?
Well, not exactly, because "Space" is a modifier, just like "Alt" or "Ctrl", so it could be harder.
Florian Bruhin, aka The-Compiler, who is qutebrowser's primary maintainer, talked about this topic in [[https://github.com/qutebrowser/qutebrowser/issues/319][this GitHub issue]] (discovered through [[https://www.reddit.com/r/qutebrowser/comments/6gvh7e/keychains_with_modifiers/][this reddit post]]).
Luckily for me, the problem was solved with a [[https://github.com/qutebrowser/qutebrowser/pull/3647][proper key handling refactoring of 2018]] (thanks, Florian, this is really appreciated).
Right now, chaining modifiers and letters is /that/ easy.

So, stopping all the chit-chat, how do we set a keychain/sequence with the space modifier?

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# Opening new pages like I open new files.
config.bind('<Space>ff', 'set-cmd-text -s :open')
#+end_src

Pretty simple, right?:

Since we're going to use =<Space>= a lot, it's better to unbind the =<Space>= key from its use in caret mode. You know, it shouldn't be a problem, but it's better to be careful.

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# Selection toggle is already taken by `v`, so I can free the spacebar
config.unbind('<Space>', mode="caret")
#+end_src

More space-keychains from here on.

*** History and bookmarks
#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# Go back in the history of the current tab.
# (like kill buffer, because usually this fall back to the previous buffer)
config.bind('<Space>bk', 'back')

# Show all bookmarks/quickmarks
config.unbind('Sb') # --jump
config.unbind('Sq') # no jump; what the hell is this jump flag anyway?
config.bind('<Space><Return>', 'bookmark-list --jump')

# Show browsing history
config.unbind('Sh')
config.bind('<Space>h', 'history')
#+end_src

*** Settings
I never access settings from inside qutebrowser, so we can disable this keychain.
However, it would be easy to launch as command.

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# Set an option
config.unbind('Ss')
# config.bind('<Space>ss', 'set')
#+end_src

*** Macros
#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# Start or stop recording a macro
# This isn't really evilish, I just prefer it this way because I happen to press q
config.unbind('q')
config.bind('<Space>q', 'macro-record')
#+end_src

*** Tabs
#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# Duplicate the current tab
config.unbind('gC')
# (like buffer clone)
config.bind('<Space>bc', 'tab-clone')

# Select tab by index or url/title best match
config.unbind('gt')
# (like ibuffer)
config.bind('<Space>bi', 'tab-select')

# Close the current/[count]th tab
config.unbind('d')
# (like kill buffer)
config.bind('<Space>bd', 'tab-close')

# Switch to the next tab
config.unbind('J')
# (like next buffer)
config.bind('<Space>bn', 'tab-next')

# Switch to the previous tab
config.unbind('K')
# (like previous buffer)
config.bind('<Space>bp', 'tab-prev')

# Close all tabs except for the current one
config.unbind('co')
# (like kill buried buffers)
config.bind('<Space>bZ', 'tab-only')

# Pin/unpin the current/[count]th tab
config.unbind('<Ctrl-p>')
# (like "buffer pin")
config.bind('<Space>p', 'tab-pin')

# Select the tab given as argument/[count]
config.unbind('T')
# (like "buffer tabs...")
config.bind('<Space>t', 'set-cmd-text -sr :tab-focus')
#+end_src

I'll keep adding Space keychains in other section of this file too.

*** Safer reload page
Having the =reload= command simply binded to =r= is dangerous, because if you forgot being in normal mode while you're writing, just by typing 'r' you risk losing all your progress in that page. Maybe you wrote a lot of text in a textarea and "whoosh", everything's gone. Yeah, it sadly happened to me. What's the solution? Once again, I think it's *space*.

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
config.unbind('r')
config.bind('<Space>rr', 'reload')
#+end_src

*** Quickly open the config file
Traditionally, qutebrowser search for gvim for opening =config.py=.
That's pretty inflexible, doesn't it?

To learn how can we change its behaviour, let's see how this works.
For opening the editor, Qutebrowser is launching the =config_edit()= function under the hood (from =qutebrowser/config/configcommands.py=):

#+begin_src python
@cmdutils.register(instance='config-commands')
    def config_edit(self, no_source: bool = False) -> None:
        """Open the config.py file in the editor.
        Args:
            no_source: Don't re-source the config file after editing.
        """
        def on_file_updated() -> None:
            """Source the new config when editing finished.
            This can't use cmdutils.CommandError as it's run async.
            """
            try:
                configfiles.read_config_py(filename)
            except configexc.ConfigFileErrors as e:
                message.error(str(e))

        ed = editor.ExternalEditor(watch=True, parent=self._config)
        if not no_source:
            ed.file_updated.connect(on_file_updated)

        filename = standarddir.config_py() # <-- THE FILENAME IS HARDCODED!
        ed.edit_file(filename)
#+end_src

Since the filename is hardcoded, I think it's better to get a totally different path for reaching this goal. I think it would be pretty out of scope to make a PR for reloading config for an org-mode literate configuration which should be tangled before being reloaded. Feels like a "slightly" niche case.

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# TODO Writing an userscript to bind here!
# config.bind('<Space>oc', '')
#+end_src

** Vim-like navigation in command mode
#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
config.bind('<Ctrl-j>', 'completion-item-focus --history next', mode="command")
config.bind('<Ctrl-k>', 'completion-item-focus --history prev', mode="command")
#+end_src

** Paste like in a terminal emulator :noexport:
I'm used to paste strings with =<Ctrl-Shift> v=, so let's teach that to qutebrowser.

# :tangle ~/.config/qutebrowser/config.py
#+begin_src python :noweb no-export
config.bind('<Ctrl-Shift> v', 'fake-key -g <Ctrl-v>')
#+end_src

This is a system-wide keybinding that qutebrowser inherit from Qt, so we can [[https://www.reddit.com/r/qutebrowser/comments/j2vykm/comment/g7ba3bs/?utm_source=share&utm_medium=web2x&context=3][emulate the behaviour]] by simulating actual =<Ctrl-v>=.

/*Not tangled, it doesn't work*/

** Sessions
For qutebrowser, sessions are just lists of URL to be opened in new tabs.
The relevant commands are:
- =session-delete=
- =session-load=
- =session-save=

Every command request an argument, the name of the session.

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
config.bind('<Space>ss', 'set-cmd-text -s :session-save')
config.bind('<Space>sl', 'set-cmd-text -s :session-load')
config.bind('<Space>sd', 'set-cmd-text -s :session-delete')
#+end_src

This way, sessions are easier to inspect, because by using =set-cmd-text= we evoke the "sessions" prompt.

** Wordreference
Search a word on wordreference (italian - english):

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
config.bind('<Space>wr', 'set-cmd-text :open https://www.wordreference.com/iten/')
#+end_src

* Dark mode
Basically, this inverts color pages.

# :tangle ~/.config/qutebrowser/config.py
#+begin_src python :noweb no-export
config.set("colors.webpage.darkmode.enabled", True)
#+end_src

I don't tangle this anymore, because I think it's too annoying, *but* it would be nice to bind something similar to a command.

* Theme
In the past commits, you can see I dumped all the colors instructions here in the config, but it's basically a mess. Now I externalized my theme-related configuration in a [designated repository (@gicrisf/qute-city-lights)](https://github.com/gicrisf/qute-city-lights), then cloned it in the =themes= subdir. This way, just sourcing it with this simple command does the magic.

#+begin_src python :tangle ~/.config/qutebrowser/config.py
config.source('themes/qute-city-lights/city-lights-theme.py')
#+end_src

* Killing cookie banners
Using this Rust userscript made by [[https://github.com/Schmiddiii][Schmiddiiii]].
As he say in [[https://www.reddit.com/r/qutebrowser/comments/mnptey/comment/gwrtipp/?utm_source=share&utm_medium=web2x&context=3][this Reddit thread]], this userscript

#+begin_quote
has to be called every time you want to block a banner (I dont know if it is possible to call the script when changing the website). The script also aims to reject all cookies instead of hiding the banner, as just hiding it will bring it up again when reloading. *I recommend setting up a key binding.*
#+end_quote

We'll think later about the keybinding; install it first:
- Git clone [[https://github.com/Schmiddiii/qute-cookie-block/][this repo]];
- Execute the =make.sh= in the directory;
- Import a blocklist (compatible with ublock-origin) as =~/.local/qutebrowser/cookie-blockers/blocklist.txt=;
- Done!

This is a nice example because of the implementations itself. Extending qutebrowser functionalities in Rust is interesting for a lot of reasons.
Whatever, now it's time to define the keybinding:

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# scb: spawn cookie block
config.bind('<Space>cb', ':spawn --userscript qute-cookie-block')
#+end_src

A softer alternative was presented by LordOfTheAssClowns [[https://www.reddit.com/r/qutebrowser/comments/mnptey/comment/gu4m9ht/?utm_source=share&utm_medium=web2x&context=3][on the same thread]]:

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# kse: kill sticky elements
config.bind('kse', 'jseval (function () { '+
'  var i, elements = document.querySelectorAll("body *");'+
''+
'  for (i = 0; i < elements.length; i++) {'+
'    var pos = getComputedStyle(elements[i]).position;'+
'    if (pos === "fixed" || pos == "sticky") {'+
'      elements[i].parentNode.removeChild(elements[i]);'+
'    }'+
'  }'+
'})();');
#+end_src

/(Watch out! This block isn't tangled)/

This evaluate this javascript function to shut off floating thingies sticked to your viewport.
Less sofisticated, but looks effective enough.

Potential improvements:
- Most pages block scrolling while showing the banner. This problem must be addressed (simply by tweaking the css);

* Tabs
** Hide single tab
Don't show the tabs bar, if there's a single tab opened.

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
c.tabs.show = "multiple"
#+end_src

* Aliases

Close the tab with =:q=.

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# use `:q` command for killing the tab, not the window
c.aliases['q'] = "tab-close"
#+end_src

You can always close the window with the standard =:qa= (quit all) command.

* Statusbar
** Widgets

#+begin_quote
List of widgets displayed in the statusbar.

Type: [[https://qutebrowser.org/doc/help/settings.html#types][List of StatusbarWidget]]

Valid values:
- url: Current page URL.
- scroll: Percentage of the current page position like 10%.
- scroll_raw: Raw percentage of the current page position like 10.
- history: Display an arrow when possible to go back/forward in history.
- search_match: A match count when searching, e.g. Match [2/10].
- tabs: Current active tab, e.g. 2.
- keypress: Display pressed keys when composing a vi command.
- progress: Progress bar for the current page loading.
- text:foo: Display the static text after the colon, foo in the example.
- clock: Display current time. The format can be changed by adding a format string via clock:.... For supported format strings, see the Python datetime documentation.

Default:
- keypress
- search_match
- url
- scroll
- history
- tabs
- progress
#+end_quote

I appreciate the standard.
Doing nothing here.
* Minimize fingerprinting
From [[https://wiki.archlinux.org/title/Qutebrowser][Arch Wiki]]:

#+begin_quote
Websites may be able to identify you based on combining information on screen size, user-agent, HTTP_ACCEPT headers, and more. See [2] for more information and to test the uniqueness of your browser. Below are a few steps that can be taken to make your qutebrowser installation more "generic".
#+end_quote

You can test how well you're protected for tracking and fingerprinting by using [[https://coveryourtracks.eff.org/https://coveryourtracks.eff.org/][this tool (by Electronic Frontier Foundation)]].

** Set a common user-agent

#+begin_quote
Several user agents are available as options.
#+end_quote

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
c.content.headers.user_agent = "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
#+end_src

** Set a common HTTP_ACCEPT header
#+begin_quote
The following is a common HTTP_ACCEPT header (Firefox default).
#+end_quote

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
c.content.headers.accept_language = "en-US,en;q=0.5"
c.content.headers.custom = {"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"}
#+end_src

** Disable reading from canvas
#+begin_quote
Note: [[https://github.com/qutebrowser/qutebrowser/issues/2908][Some websites]] depend on canvas reading for content rendering and other functionality. Adding this option may cause them to not work properly.
#+end_quote

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
c.content.canvas_reading = False
#+end_src

** Disable WebGL

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
c.content.webgl = False
#+end_src

* Brave Adblocker
=python-adblock= is a python wrapper around the Brave Rust library. Install it with pacman:

#+begin_src bash
sudo pacman -S python-adblock
#+end_src

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
c.content.blocking.method = "both"
#+end_src

* Password manager
I use [[https://bitwarden.com/][Bitwarden]] as password manager.
I was thinking about using some kind of wrapper around Bitwarden CLI. See:
- [[https://github.com/mattydebie/bitwarden-rofi][bitwarden-rofi]]
- [[https://github.com/Sife-ops/dmenu_bw][dmenu_bw]]

In the meantime, I'm using the Electron app.
The integration isn't good enough, so I'm not satisfied, but this problem can wait.

* Containers
I love Multi-Account Containers in Firefox and I'd like to have containers in qutebrowser too.
Is this possible? Not exactly. There's a [[https://github.com/qutebrowser/qutebrowser/issues/4102][GitHub issue about this topic]].

As Florian Bruhin points out:
#+begin_quote
[[https://github.com/s-praveen-kumar][@s-praveen-kumar]] has written an userscript to manage different basedirs in a container-like way - see [[https://github.com/qutebrowser/qutebrowser/discussions/7325][#7325]].
#+end_quote

So, let's see what [[https://github.com/qutebrowser/qutebrowser/discussions/7325][#7325]] is about:

#+begin_quote
This allows multiple containers for multiple accounts or to prevent cookie tracking across sites.
Check it out here: [[https://github.com/s-praveen-kumar/qute-containers][qute-containers]]
#+end_quote

From the qute-containers readme:

#+begin_quote
Browser Containers is a feature available as an official extension in Mozilla Firefox. It allows users to have separate 'containers'. All the browser data, cookies and site storage are stored and separated within these containers. Common use cases include having multiple containers to mitigate cookie tracking and using multiple web logins without confusion (Eg: Multiple gmail accounts).
#+end_quote

I like this idea because I could write a specific container configuration to maintain my container preferences in plain text.
One could assign an accent color for each container by assigning a specific =config.py=. It would be nice to generate config files from the main one, in order to make the main =config.py= a matrix for the derived container children.

But let's stick to the current solutions before biting off more than we can chew.

#+begin_quote
The script creates a file with a list of containers in the location specified by =CONTAINER_LIST= variable in the =containers_config= file.

The actual containers are created as directories within the =CONTAINER_BASE= directory.

Containers can be created or deleted manually by editing the =CONTAINER_LIST= file and creating/removing respective directory from =CONTAINER_BASE=. Helper scripts are provided to make this process easier.
#+end_quote

With this solution, we would run multiple instances of qutebrowser. Therefore, a memory problem could emerge.
[[https://github.com/qutebrowser/qutebrowser/issues/4102#issuecomment-852182640][Like @markstos said]]:

#+begin_quote
I regularly have 4 different profiles running and also have near-daily out-of-memory problems on a laptop with 16GB of RAM. When I killall qutebrowser, memory recovers to less than 2GB of usage.

So while I like the simplicity and isolation of using separate browser profiles, it seems there is a memory penalty to pay with some duplicated browser code loaded 4x. If a "Firefox containers" type of solution could result in significant memory savings, that would be welcome!
#+end_quote

I don't like to say that, but untile qutebrowser doesn't catch up with the Firefox way to manage containers, the best solution could be using Firefox for some stuff and qutebrowser for other stuff.
I avoid to be to drastic, because I think I should play with profiles, before choosing a definitive workflow.

* Sharing sessions
To share my sessions across different machines, I stowed* my =~/.local/share/qutebrowser/sessions/= directory from my Dropbox. I mean I'm using GNU Stow: basically, I'm just symlinking the directory from a cloud. Of course, one could use any cloud (or even git, but I don't like version-controlling such ephemeral data).

* Save as ebook
I could make an userscript to download as epub/mobi.
# Readability JS in common lisp could be useful ?

# * TODO Kaomoji
# * TODO Music management
# I like listening to lofi youtube playlists and I get frustrated when they go offline, so I would like to download my favorite ones while I listen to them.

* Minimize CPU usage
Just looking at htop, looks like qutebrowser use more CPU than Firefox (in comparable conditions). It's just a vague and empirical observation, but it wouldn't surprise me if qutebrowser was less optimized than Firefox or other big corporate browsers like Chrome, Edge or other Chromium based one. As Florian points out [[https://github.com/qutebrowser/qutebrowser/issues/5375][in this GitHub issue]], this problem probably lies outside qutebrowses's development domain, since KDE Falcon (another QtWebEngine based browser) shows up similar CPU usage.

What can we do to restrain the extent of this problem?

** Disable JS
By disabling JS globally and enabling it on demand when strictly needed, we could largely reduce the basal CPU usage *and* minimize fingerprinting too.


#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# Disable JS globally
# c.content.javascript.enabled = False
# This is an equivalent form, I re-write in this other form for uniformity's sake in this particular block.
config.set('content.javascript.enabled', False)

# Enable it on DDG
config.set('content.javascript.enabled', True, '*://duckduckgo.com/')
#+end_src

Keybindings:

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# javascript enable
config.bind('<Space>je', ':set content.javascript.enabled true')

# javascript disable
config.bind('<Space>jd', ':set content.javascript.enabled false')
#+end_src

* Redirects (SwapForQute)
** Introduction to SwapForQute
Having JS disabled implies a worst experience on particular frontends.
# Per minimizzare il nostro bisogno di JS, meglio passare su frontend più leggeri quando possibile.

# Redirect reddit pages to old.reddit pages
# use qutebrowser apis like this guy https://github.com/Xian-beep/qutebrowser-redirect
# to map pages, regex are needed

[[https://github.com/qutebrowser/qutebrowser/issues/5476][This problem is known to the community]], although there isn't an idiomatic solution. I think it's fundamental having the redirect to happen *before the page loads*, as it happens in a lovely userscript, which is [[https://codeberg.org/mister_monster/qutebrowser-url-mutator][Qutebrowser URL Mutator]].

Although I liked the idea of Qutebrowser URL Mutator, in the end I chose to not use it because some concerns I had. Particularly, I thought that regexes are good for specific solutions that you solve on place and basically never touch again, but I didn't like the idea to have them in a config file, which is usually meant to be read and edited every now and then.

I would have preferred an implementation that leverage standard library functions for managing URLs. Usually, this is a better solution to avoid quirky bugs in the long run. So, I decided to write a new userscript myself and that's how SwapForQute was born.
[[https://github.com/gicrisf/qute-url-replacer][Check the repository to learn more about it]].

How do we configure it? The userscript essentially gets instruction from a JSON file: you can choose where it should live, but I suggest putting it into a predictable and absolutely boring directory like =~/.config/qutebrowser/userscripts/swapforqute/config.json=. But why not YAML? Why not TOML? Because the file isn't thought to be manually written. You can, if you want to, but I think it's better systematically producing it from a python dictionary like the following:

# - Easy to edit configuration;
# - No regex, because every step is built on standard libraries;

# Moreover, even though I love TOML, I don't want to maintain two (or more) config files across my machines, just for running the browser. It would be better to write our preferences directly in =config.py=. I was thinking about dumping a python dictionary via JSON.
# Since binding the command to qutebrowser implies string transformations somewhere, this isn't a safe strategy. It's better to load the config from a separate file. Since we're in org-mode, this is pretty easy. Just tangle it in =url_replacer.json=.

#+begin_src python
url_replacer = {
    "www.reddit.com" : {
        "out": "old.reddit.com",
        "force_https": True,
        "clean_queries": True
    },
    "reddit.com": {
        "out": "old.reddit.com",
        "force_https": True,
        "clean_queries": True
    },
}
#+end_src

#+begin_quote
Wait, this is so redundant, this is so awful!
#+end_quote

You could over-complicate a small python dictionary for saving a bunch of kBs or be a free animal.
If, like me, you cannot resist the urge to be the slave of little silly idyosyncrasies, probably you will immediately see the point of generating the JSON from a Python dictionary.

#+begin_src python :noweb no-export :results output
url_replacer = dict()
url_replacer["www.reddit.com"] = { "out": "old.reddit.com", "force_https": True, "clean_queries": True }
url_replacer["reddit.com"] = url_replacer["www.reddit.com"]
#+end_src

Of course this isn't relevant with two redirects only, but it could became relevant with a lot of items.

** The actual configuration
I'll store here after my actual configuration for the swapforqute userscript.

#+name:url-replacer-conf
#+begin_src python :noweb no-export :results output
url_replacer = dict()

url_replacer["www.reddit.com"] = {
    "out": "old.reddit.com",
    "force_https": True,
    "clean_queries": True
}

url_replacer["reddit.com"] = url_replacer["www.reddit.com"]

import json
print(json.dumps(url_replacer))
#+end_src

This is dumped as JSON string, therefore org-mode's noweb can automatically generate the new result and tangling it in the desired directory.

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/userscripts/swapforqute/config.json
<<url-replacer-conf()>>
#+end_src

** Permissions
Before doing anything, we must be sure the script has permissions to be runned by the system:

# Spiega meglio che devi applicarlo allo script nella sua cartella

If you installed the script in =~/.config/qutebrowser/userscripts/swapforqute/main.py=, launch

#+begin_src sh
chmod +x ~/.config/qutebrowser/userscripts/swapforqute/main.py
#+end_src

** Building the command
Now, we can let qutebrowser trying to spawn it with a command. How this command's made?
First of all, it will start with =:spawn --userscript=, like every other qutebrowser's userscript.

Then we must give him:
- The absolute or relative (to the =/userscript= directory) position of the script;
- =-c=, which is the config argument, with the location of the configuration json.

In pythonic words,

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
sfq_base_dir = "~/.config/qutebrowser/userscripts/swapforqute/"
sfq_script_path = sfq_base_dir + "main.py"
sfq_conf_path = sfq_base_dir + "config.json"
sfq_cmd = "--userscript {} -c {}".format(sfq_script_path, sfq_conf_path)
#+end_src

This command still lacks an argument:
- =-u=, which is the URL we need to check and refine;

Of course, while the previous components of the command are statically defined when we launch the browser instance, this argument must be defined each time we open a relevant URL: that's why we're going to left =-u= at the tail.

** Alias and keybindings
It's not feasible to write all the command's clutter everytime.
Better writing a simple alias like =:sfq=.

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
c.aliases['sfq'] = "set-cmd-text -s :spawn {} -u ".format(sfq_cmd)
#+end_src

The obvious next step is setting up the keybindings.

# TODO Devo scrivere lo schemino di come funziona tipo mermaid!

#+begin_src python :noweb no-export :tangle ~/.config/qutebrowser/config.py
# Replace URLs on :open
# The following are equivalent!
# We can bind the commands to an alias or directly.
# config.bind('o', "set-cmd-text -s :spawn {} -u ".format(sfq_cmd))
# config.bind('o', ':sfq')

# config.bind('O', "set-cmd-text -s :spawn {} -u ".format(sfq_cmd))

# Replace URLs from hints
config.bind('f', "hint links spawn {} --cmd 'open' -u ".format(sfq_cmd) + " {hint-url}")
config.bind('F', "hint links spawn {} --cmd 'open -t' -u ".format(sfq_cmd) + " {hint-url}")

# Special command for opening
# config.bind('<Space>re', "set-cmd-text -s {} -u ".format(sfq_cmd))
#+end_src

Since *I don't want all URLs to be parsed and filtered* by this script, I don't bind it to =o= and =O=, but you can still read it how it should be made because I left the bindings commented out.

# TODO wordreference userscript!
# SPCwr è libera!

# TODO fai lo script shell di installazione

** What SFQ do

A d2 diagram.

#+begin_src d2 :file test.png
# OS
qute_fifo: QUTE FIFO

qutebrowser: Qutebrowser {
  cmd: SFQ command
}

pyenv: Py env {
  sfq_script: SFQ script
  sfq_conf: JSON conf. file
  sfq_conf.shape: document

  sfq_script -> sfq_conf: Read file
  sfq_conf -> sfq_script: Get dict.
}

qutebrowser.cmd -> pyenv.sfq_script: Original URL
pyenv.sfq_script -> qute_fifo: New URL
qute_fifo -> qutebrowser
#+end_src

Another, simpler, d2 diagram.

#+begin_src d2 :file short.png
qutebrowser: Qutebrowser {
  ori_url: "https://www.reddit.com/<...>/?utm_source=<...>"
  ori_url.style.fill: "#e55f5f"
  ori_url.shape: parallelogram
}

sfq: SwapForQute userscript

new_url: "https://old.reddit.com/<...>/"
new_url.style.fill: "#ACE1AF"
new_url.shape: parallelogram

qutebrowser.ori_url -> sfq -> new_url -> qutebrowser
#+end_src

Something like "https://www.reddit.com/r/emacs/comments/yubhff/zwitterionic_digressions_get_user_inputs_in_emacs/?utm_source=share&utm_medium=web2x&context=3" magically becames "https://old.reddit.com/r/emacs/comments/yubhff/zwitterionic_digressions_get_user_inputs_in_emacs"
